# Generated by Django 5.2.1 on 2025-06-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='type_rela',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='favourite',
        ),
    ]
