# Generated by Django 5.2.1 on 2025-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0002_rename_type_rela_tool_type_remove_tool_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
