# Generated by Django 5.2.1 on 2025-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0003_tool_date_added_tool_date_updated_tool_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='date_added',
        ),
        migrations.AddField(
            model_name='tool',
            name='date_addeds',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
