# Generated by Django 5.2.1 on 2025-06-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0004_remove_tool_date_added_tool_date_addeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='date_addeds',
            new_name='date_added',
        ),
    ]
