# Generated by Django 5.2.1 on 2025-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0005_rename_date_addeds_tool_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='logo',
            new_name='logo_url',
        ),
        migrations.AddField(
            model_name='tool',
            name='rank_in_category',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
