# Generated by Django 5.2.1 on 2025-06-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0006_rename_image_tool_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
