# Generated by Django 5.2.1 on 2025-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0007_alter_tool_image_url_alter_tool_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
