# Generated by Django 5.2.1 on 2025-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunt_app', '0008_category_description_hashtag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
